### ISSUE TITLE
device tree compiler link broken

### ISSUE THREAD

**Issue by marinjurjevic** [coderbyheart/fw-nrfconnect-nrf-docker#10]
Link to debian package from kernel.org is broken. Perhaps just name changed, anyway should be updated to http://mirrors.edge.kernel.org/ubuntu/pool/main/d/device-tree-compiler/device-tree-compiler_1.4.7-3ubuntu2_amd64.deb

**Comment by coderbyheart** [comment]
Fixed via #12
