### ISSUE TITLE
docker build does not fail on wget error

### ISSUE THREAD

**Issue by marinjurjevic** [coderbyheart/fw-nrfconnect-nrf-docker#11]
https://github.com/coderbyheart/fw-nrfconnect-nrf-docker/blob/0c0aefa9b5a338578bde29d83d5e184abcbe475e/Dockerfile#L21-L27

Using `;` in middle of `&&` chain is wrong as it won't stop docker build. Issue is that docker only checks last returned error and `;` stops error propagation.
Issue #10 will cause line 22 to fail which will propagate to line 27 (lines 24-26 are not executed) where propagation stops. Starting with line 29 build continues normally which should not happen. 

Solution: don't use `;` so failing commands are detected more easily. Also I think quiet flags are questionable in these kind of scenarios as we want to be aware of commands failing.

**Comment by coderbyheart** [comment]
Thanks we missed this when reducing the number of `RUN` instructions in #5.

Fixed via #12
