### ISSUE TITLE
Device Tree Compiler link is broken again...

### ISSUE THREAD

**Issue by ApplicationNinja** [coderbyheart/fw-nrfconnect-nrf-docker#21]
The following no longer exists:

http://mirrors.edge.kernel.org/ubuntu/pool/main/d/device-tree-compiler/device-tree-compiler_1.4.7-3ubuntu2_amd64.deb

Needs to be updated to:

http://mirrors.edge.kernel.org/ubuntu/pool/main/d/device-tree-compiler/device-tree-compiler_1.6.0-1_amd64.deb

**Comment by coderbyheart** [comment]
Thanks, they keep removing the old versions, ... and I broke the daily test run in 45e4bd8d8d855504ffeabfabfd0df09007a66771.

On it!

**Comment by ApplicationNinja** [comment]
Looks like further updates are needed as well with 1.6.0:

dpkg: dependency problems prevent configuration of device-tree-compiler:
 device-tree-compiler depends on libfdt1 (>= 1.6.0); however:
  Package libfdt1 is not installed.
 device-tree-compiler depends on libyaml-0-2; however:
  Package libyaml-0-2 is not installed.

**Comment by coderbyheart** [comment]
It's fixed now.
Thanks again for bringing this to my attention!

**Comment by ApplicationNinja** [comment]
> It's fixed now.
> Thanks again for bringing this to my attention!

Thanks, however did you see my other comment as well? I had to add libfdt1 and libyaml-0-2 to the Dockerfile as well in order to fix this new 1.5.1 dependency...

**Comment by coderbyheart** [comment]
Yes:

https://github.com/coderbyheart/fw-nrfconnect-nrf-docker/blob/be2d9d8dafc46cc629faea06b16dac40ca9e98d8/Dockerfile#L17

**Comment by ApplicationNinja** [comment]
> Yes:
> 
> https://github.com/coderbyheart/fw-nrfconnect-nrf-docker/blob/be2d9d8dafc46cc629faea06b16dac40ca9e98d8/Dockerfile#L17

Ahh... sorry, missed that! :)
